import categoryRecords from '../content/categories.json';
import projectRecords from '../content/projects.json';
import dashboardRecords from '../content/dashboards.json';
import experienceRecords from '../content/experience.json';
import educationRecords from '../content/education.json';
import profileRecord from '../content/profile.json';
import siteRecord from '../content/site.json';
import contract from '../../docs/cms-content-schema.json';
import { normalizeContent } from './normalize-content.mjs';

export const site = normalizeContent(siteRecord, contract.$defs.site) as typeof siteRecord;
export const profile = normalizeContent(profileRecord, contract.$defs.profile) as typeof profileRecord;
export const education = normalizeContent(educationRecords, contract.$defs.education) as typeof educationRecords;
export const categories = normalizeContent(categoryRecords, contract.$defs.categories) as typeof categoryRecords;
export const labels = site.labels;
const presentationOrder = (a: {featured: boolean; displayOrder: number}, b: {featured: boolean; displayOrder: number}) => Number(b.featured) - Number(a.featured) || a.displayOrder - b.displayOrder;
export const projects = (normalizeContent(projectRecords, contract.$defs.projects) as typeof projectRecords).sort(presentationOrder);
export const dashboards = (normalizeContent(dashboardRecords, contract.$defs.dashboards) as typeof dashboardRecords).sort(presentationOrder);
export const experiences = (normalizeContent(experienceRecords, contract.$defs.experience) as typeof experienceRecords).sort((a, b) => presentationOrder(a, b) || b.start.localeCompare(a.start));
export const categoryLabel = (id: string) => categories.find(item => item.id === id)?.label ?? id;
const previewRevision = import.meta.env.PORTFOLIO_PREVIEW === 'true' ? import.meta.env.PORTFOLIO_REVISION : '';
export const sitePath = (path = '') => `${import.meta.env.BASE_URL}${path.replace(/^\//, '')}${previewRevision && (!path || path.endsWith('/')) ? `?v=${previewRevision}` : ''}`;
export const mediaPath = (path: string) => path.startsWith('https://') ? path : sitePath(path);
export type Project = typeof projects[number];
export type Dashboard = typeof dashboards[number];
export const usableLink = (url: string) => /^https:\/\//.test(url) || /^\/(?!\/)/.test(url);
